name: bely_boutique_princess
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  curved_navigation_bar: ^1.0.3
  equatable: ^2.0.3
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  firebase_auth: ^3.3.16
  firebase_core: ^1.16.0
  fluttertoast: ^8.0.9
  intl:
  carousel_slider: ^4.1.1
  flutter_services_binding: ^0.1.0
  image_picker: ^0.8.4+9
  firebase_storage: ^10.0.3
  cloud_firestore: ^3.1.14
  uuid: ^3.0.5
  # animated_splash_screen: ^1.2.0
  # smooth_page_indicator: ^1.0.0+2
  animations: ^2.0.3
  pinch_zoom: ^1.0.0
  url_launcher: ^6.1.2
  flutter_settings_ui: ^2.0.1
  multi_select_flutter: ^4.1.2
  fl_chart: ^0.36.1
  data_table_2: ^2.0.3
  flutter_svg: ^0.22.0
  flutter_custom_dialog: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/Source_sans_pro/SourceSansProSemiBold.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/facebook_64.png
    - assets/images/whatsapp_64.png
    - assets/images/profile_pic.png
    - assets/images/loading_gif.gif
    - assets/videos/
flutter_intl:
  enabled: true
  main_locale: es
  class_name: S